### PR TITLE
clarify Meta is allowed in one special case

### PR DESCRIPTION
**Pull request by jmandel**
http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/#identity-assurance wound up using Meta for one purpose.

### CODE REVIEW

**Comment by jmandel** [comment]
FYI @smart-on-fhir/health-cards-early-adopters

**Comment by masnick** [comment]
We are going to update the IG to reflect this as well.

**Comment by christianpaquin** [comment]
Would you also update the version number?

**Comment by jmandel** [comment]
> Would you also update the spec version number?

Added!

**Comment by christianpaquin** [comment]
Just for planning purposes, how long is the review period before PRs are merged?

**Comment by jmandel** [comment]
We haven't standardized this -- but I'm thinking 2 days as a general target in cases where nobody has concerns. I'm planning to merge this today.

**Pull request merged**
